version: "3.8"
services:
  skuld:
    image: bastihav/skuld:latest
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - G:/skuld:/trees
    #command: -c "<path to config file>"
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #web-app:
   # build: ./web-app
    #ports:
     # - "443:443"
